### ISSUE TITLE
嗨，请问这部分如何获取到正常看的懂的字符呀？如何转换

### ISSUE THREAD

**Issue by AdminQQZ** [wave-chtj/BaseIotUtils#1]
@Override
            public void recv(byte[] data, int offset, int size) {
                LogUtil.e("qqz>>>", "recv-size" + size);

            }

**Comment by wave-chtj** [comment]
参照HexUtils 中对应的方法噢，

**Comment by AdminQQZ** [comment]
好，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"wave_chtj"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月22日(星期五) 晚上6:19
收件人:&nbsp;"wave-chtj/BaseIotUtils"<BaseIotUtils@noreply.github.com&gt;;
抄送:&nbsp;"867711323"<867711323@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wave-chtj/BaseIotUtils] 嗨，请问这部分如何获取到正常看的懂的字符呀？如何转换 (#1)




参照HexUtils 中对应的方法噢，
